default: &default
  adapter: postgresql
  reconnect: true
  encoding: utf8
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host:     <%= ENV['POSTGRESQL_HOST'] || '127.0.0.1' %>
  port:     <%= ENV['POSTGRESQL_PORT'] %>

development:
  <<: *default
  database: <%= ENV['POSTGRESQL_DATABASE'] %>

test: &test
  <<: *default
  database: <%= ENV['POSTGRESQL_DATABASE_TEST'] %>

production:
  <<: *default
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
